[package]
name = "biodb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.1", features = ["derive"] }
bio = "0.39.2"
plotters = "0.3.1"
colorous = "1.0.6"
anyhow = "1.0.55"